    <link href="{{lodspk.home}}css/bootstrap.min.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="{{lodspk.home}}css/bootstrap-responsive.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="{{lodspk.home}}css/basic.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="{{lodspk.home}}css/ui.css" rel="stylesheet" type="text/css" media="screen" />
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.min.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/bootstrap.js"></script>
