    <link href="{{lodspk.home}}css/bootstrap.min.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="{{lodspk.home}}css/bootstrap-responsive.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="{{lodspk.home}}css/basic.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="{{lodspk.home}}css/ui.css" rel="stylesheet" type="text/css" media="screen" />
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.min.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.autocomplete-min.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/bootstrap.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.json-1.3.min.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.uri.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.xmlns.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.curie.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.datatype.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.rdf.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.rdfa.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.rules.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.rdf.xml.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.rdf.json.js"></script>
    <script type="text/javascript" src="{{lodspk.home}}js/jquery.rdf.turtle.js"></script>

