<header class="jumbotron subhead" id="overview">
  <h1><a href='{{lodspk.home}}'>Poderopedia</a></h1>
  <p class="lead">Utilice el menú para acceder a las diferentes funcionalidades.</p>
  <div class="subnav">
    <ul class="nav nav-pills">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="{{lodspk.home}}#">Personas<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{{lodspk.home}}instances/foaf:Person">Listado de Personas</a></li>
          <li><a href="{{lodspk.home}}create/foaf:Person">Agregar nueva persona</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="{{lodspk.home}}#">Empresas<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{{lodspk.home}}instances/vocab:Company">Listado de Empresas</a></li>
          <li><a href="{{lodspk.home}}create/vocab:Company">Agregar nueva empresa</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="{{lodspk.home}}#">Organizaciones<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{{lodspk.home}}instances/vocab:Organization">Listado de Organizaciones</a></li>
          <li><a href="{{lodspk.home}}create/vocab:Organization">Agregar nueva organización</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="{{lodspk.home}}#">Eventos<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{{lodspk.home}}instances/vocab:NewsEvent">Listado de Eventos</a></li>
          <li><a href="{{lodspk.home}}create/vocab:NewsEvent">Agregar nuevo evento</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="{{lodspk.home}}#">Conexiones<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{{lodspk.home}}create/vocab:EconomicConnection">Agregar conexión económica</a></li>
          <li><a href="{{lodspk.home}}create/vocab:AcademicConnection">Agregar conexión académica</a></li>
          <li><a href="{{lodspk.home}}create/vocab:BelongingConnection">Agregar conexión de pertenencia</a></li>
          <li><a href="{{lodspk.home}}create/vocab:BelongingConnection">Agregar conexión de pertenencia</a></li>
        </ul>
      </li>
    </ul>
  </div>
</header>

