<header class="jumbotron subhead" id="overview">
  <h1><a href='{{lodspk.home}}'>Poderopedia</a></h1>
  <p class="lead">Utilice el menú para acceder a las diferentes funcionalidades.</p>
  <div class="subnav">
    <ul class="nav nav-pills">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="{{lodspk.home}}#">Personas<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{{lodspk.home}}instances/foaf:Person">Listado de Personas</a></li>
          <li><a href="{{lodspk.home}}create/foaf:Person">Agregar nueva persona</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Organizaciones<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{{lodspk.home}}instances/vocab:AcademicOrganization">Listado de Organizaciones académicas</a></li>
          <li><a href="{{lodspk.home}}create/vocab:AcademicOrganization">Agregar nueva organización académica</a></li>
          <li class="divider"></li>
          <li><a href="{{lodspk.home}}instances/vocab:Company">Listado de empresa</a></li>
          <li><a href="{{lodspk.home}}create/vocab:Company">Agregar nueva empresa</a></li>
          <li class="divider"></li>
          <li><a href="{{lodspk.home}}instances/vocab:NonGovernmentalOrganization">Listado de organizaciones no gubernamental</a></li>
          <li><a href="{{lodspk.home}}create/vocab:NonGovernmentalOrganization">Agregar nueva organización no gubernamental</a></li>
          <li class="divider"></li>
          <li><a href="{{lodspk.home}}instances/vocab:RestrictedAccessOrganization">Listado de organizaciones de acceso restringido</a></li>
          <li><a href="{{lodspk.home}}create/vocab:RestrictedAccessOrganization">Agregar nueva organización de acceso restringido</a></li>
          <li class="divider"></li>
          <li><a href="{{lodspk.home}}instances/vocab:InternationalOrganization">Listado de organizaciones internacional</a></li>
          <li><a href="{{lodspk.home}}create/vocab:InternationalOrganization">Agregar nueva organización internacional</a></li>
          <li class="divider"></li>
          <li><a href="{{lodspk.home}}instances/vocab:ReligiousOrganization">Listado de organizaciones religiosas</a></li>
          <li><a href="{{lodspk.home}}create/vocab:ReligiousOrganization">Agregar nueva organización religiosas</a></li>
          <li class="divider"></li>
          <li><a href="{{lodspk.home}}instances/vocab:ProgrammaticOrganization">Listado de organizaciones programáticas</a></li>
          <li><a href="{{lodspk.home}}create/vocab:ProgrammaticOrganization">Agregar nueva organización programática</a></li>
          <li class="divider"></li>
          <li><a href="{{lodspk.home}}instances/vocab:PoliticalOrganization">Listado de organizaciones políticas</a></li>
          <li><a href="{{lodspk.home}}create/vocab:PoliticalOrganization">Agregar nueva organización política</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="{{lodspk.home}}#">Eventos<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{{lodspk.home}}instances/vocab:NewsEvent">Listado de Eventos</a></li>
          <li><a href="{{lodspk.home}}create/vocab:NewsEvent">Agregar nuevo evento</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="{{lodspk.home}}#">Conexiones<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{{lodspk.home}}create/vocab:EconomicConnection">Agregar conexión económica</a></li>
          <li><a href="{{lodspk.home}}create/vocab:AcademicConnection">Agregar conexión académica</a></li>
          <li><a href="{{lodspk.home}}create/vocab:BelongingConnection">Agregar conexión de pertenencia</a></li>
          <li><a href="{{lodspk.home}}create/vocab:PoliticalConnection">Agregar conexión política</a></li>
        </ul>
      </li>
    </ul>
  </div>
</header>

